/**
 * Referral/Affiliate System
 * Track referrals and manage commissions
 */

import { db } from '@/lib/db';
import { credits } from '@/lib/payments/credits';

/**
 * Referral status
 */
export type ReferralStatus = 'PENDING' | 'ACTIVE' | 'PAID' | 'CANCELLED';

/**
 * Referral configuration
 */
export interface ReferralConfig {
  // Default commission rate (20%)
  defaultCommissionRate: number;
  // Credits awarded to referred user on signup
  referredUserBonus: number;
  // Minimum payout threshold
  minPayoutAmount: number;
}

/**
 * Default referral configuration
 */
export const defaultReferralConfig: ReferralConfig = {
  defaultCommissionRate: 0.20, // 20%
  referredUserBonus: 50, // 50 credits
  minPayoutAmount: 50, // $50 minimum payout
};

/**
 * Referral statistics
 */
export interface ReferralStats {
  totalReferrals: number;
  activeReferrals: number;
  totalEarned: number;
  pendingPayout: number;
  paidOut: number;
}

export const referrals = {
  /**
   * Get or generate referral code for a user
   */
  async getReferralCode(userId: string): Promise<string> {
    const user = await db.user.findUnique({
      where: { id: userId },
      select: { referralCode: true },
    });

    if (user?.referralCode) {
      return user.referralCode;
    }

    // Generate new code (already auto-generated by default in schema)
    const updated = await db.user.update({
      where: { id: userId },
      data: {
        referralCode: generateReferralCode(),
      },
      select: { referralCode: true },
    });

    return updated.referralCode!;
  },

  /**
   * Get user by referral code
   */
  async getUserByReferralCode(code: string) {
    return db.user.findUnique({
      where: { referralCode: code },
      select: {
        id: true,
        name: true,
        email: true,
      },
    });
  },

  /**
   * Create a referral when a new user signs up with a referral code
   */
  async createReferral(
    referrerCode: string,
    referredUserId: string,
    config: ReferralConfig = defaultReferralConfig
  ): Promise<{ success: boolean; message: string }> {
    // Get referrer
    const referrer = await this.getUserByReferralCode(referrerCode);
    if (!referrer) {
      return { success: false, message: 'Invalid referral code' };
    }

    // Don't allow self-referral
    if (referrer.id === referredUserId) {
      return { success: false, message: 'Cannot refer yourself' };
    }

    // Check if user was already referred
    const existingReferral = await db.referral.findUnique({
      where: { referredId: referredUserId },
    });
    if (existingReferral) {
      return { success: false, message: 'User was already referred' };
    }

    // Create referral record
    await db.referral.create({
      data: {
        referrerId: referrer.id,
        referredId: referredUserId,
        status: 'PENDING',
        commissionRate: config.defaultCommissionRate,
      },
    });

    // Award signup bonus to referred user
    if (config.referredUserBonus > 0) {
      await credits.addCredits({
        userId: referredUserId,
        amount: config.referredUserBonus,
        type: 'GRANT',
        description: 'Welcome bonus for using referral code',
        metadata: { referrerId: referrer.id },
      });
    }

    return { success: true, message: 'Referral created successfully' };
  },

  /**
   * Activate a referral (called when referred user makes first purchase)
   */
  async activateReferral(
    referredUserId: string
  ): Promise<{ success: boolean; message: string }> {
    const referral = await db.referral.findUnique({
      where: { referredId: referredUserId },
    });

    if (!referral) {
      return { success: false, message: 'No referral found' };
    }

    if (referral.status !== 'PENDING') {
      return { success: false, message: 'Referral already activated' };
    }

    // Update referral status
    await db.referral.update({
      where: { id: referral.id },
      data: { status: 'ACTIVE' },
    });

    return { success: true, message: 'Referral activated' };
  },

  /**
   * Record commission from a sale
   */
  async recordCommission(
    referredUserId: string,
    saleAmount: number
  ): Promise<{ success: boolean; commission: number }> {
    const referral = await db.referral.findUnique({
      where: { referredId: referredUserId },
    });

    if (!referral || referral.status === 'CANCELLED') {
      return { success: false, commission: 0 };
    }

    const commission = saleAmount * referral.commissionRate;

    // Update earnings
    await db.referral.update({
      where: { id: referral.id },
      data: {
        status: 'ACTIVE',
        totalEarned: { increment: commission },
      },
    });

    return { success: true, commission };
  },

  /**
   * Request payout for referral earnings
   */
  async requestPayout(
    userId: string,
    config: ReferralConfig = defaultReferralConfig
  ): Promise<{ success: boolean; message: string; amount?: number }> {
    // Calculate total unpaid earnings
    const referralData = await db.referral.aggregate({
      where: { referrerId: userId, status: 'ACTIVE' },
      _sum: {
        totalEarned: true,
        paidOut: true,
      },
    });

    const totalEarned = referralData._sum.totalEarned || 0;
    const paidOut = referralData._sum.paidOut || 0;
    const pendingPayout = totalEarned - paidOut;

    if (pendingPayout < config.minPayoutAmount) {
      return {
        success: false,
        message: `Minimum payout is $${config.minPayoutAmount}. Current balance: $${pendingPayout.toFixed(2)}`,
      };
    }

    // Mark as paid (in real implementation, this would integrate with payment system)
    await db.referral.updateMany({
      where: { referrerId: userId, status: 'ACTIVE' },
      data: {
        paidOut: { increment: pendingPayout },
        status: 'PAID',
      },
    });

    return { success: true, message: 'Payout processed', amount: pendingPayout };
  },

  /**
   * Get referral statistics for a user
   */
  async getStats(userId: string): Promise<ReferralStats> {
    const referralData = await db.referral.aggregate({
      where: { referrerId: userId },
      _count: true,
      _sum: {
        totalEarned: true,
        paidOut: true,
      },
    });

    const activeCount = await db.referral.count({
      where: { referrerId: userId, status: 'ACTIVE' },
    });

    const totalEarned = referralData._sum.totalEarned || 0;
    const paidOut = referralData._sum.paidOut || 0;

    return {
      totalReferrals: referralData._count,
      activeReferrals: activeCount,
      totalEarned,
      pendingPayout: totalEarned - paidOut,
      paidOut,
    };
  },

  /**
   * Get list of referrals for a user
   */
  async listReferrals(
    userId: string,
    options?: { limit?: number; offset?: number }
  ) {
    const { limit = 20, offset = 0 } = options || {};

    const [referralList, total] = await Promise.all([
      db.referral.findMany({
        where: { referrerId: userId },
        include: {
          referred: {
            select: {
              id: true,
              name: true,
              email: true,
              createdAt: true,
            },
          },
        },
        orderBy: { createdAt: 'desc' },
        take: limit,
        skip: offset,
      }),
      db.referral.count({ where: { referrerId: userId } }),
    ]);

    return { referrals: referralList, total };
  },

  /**
   * Generate referral link
   */
  getReferralLink(code: string): string {
    const baseUrl = process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000';
    return `${baseUrl}/register?ref=${code}`;
  },

  /**
   * Cancel a referral (admin action)
   */
  async cancelReferral(referralId: string): Promise<void> {
    await db.referral.update({
      where: { id: referralId },
      data: { status: 'CANCELLED' },
    });
  },
};

/**
 * Generate a unique referral code
 */
function generateReferralCode(): string {
  const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
  let code = '';
  for (let i = 0; i < 8; i++) {
    code += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  return code;
}
