#!/usr/bin/env npx tsx
/**
 * ShipKit Stack Selector
 * Reduces boilerplate bloat by gitignoring unused AI tool and deployment configs.
 *
 * Usage:
 *   npx tsx scripts/setup/setup-stack.ts           # Interactive mode
 *   npx tsx scripts/setup/setup-stack.ts --restore # Restore gitignored files
 *   npx tsx scripts/setup/setup-stack.ts --list    # Show current config
 */

import * as fs from 'fs';
import * as path from 'path';
import * as readline from 'readline';

// =============================================================================
// CONFIGURATION
// =============================================================================

const CONFIG_FILE = '.stack-config.json';
const GITIGNORE_MARKER = '# === ShipKit Stack Selector ===';

type CodingTool = 'claude' | 'cursor' | 'windsurf';
type DeploymentStrategy = 'vercel' | 'docker';

interface StackConfig {
  selectedAt: string;
  codingTools: CodingTool[];
  deployment: DeploymentStrategy;
  gitignored: string[];
}

const CODING_TOOL_FILES: Record<CodingTool | 'shared', string[]> = {
  claude: ['.claude/', 'CLAUDE.md'],
  cursor: ['.cursor/'],
  windsurf: ['.windsurfrules'],
  shared: ['AGENTS.md'], // Keep if any AI tool selected
};

const DEPLOYMENT_FILES: Record<DeploymentStrategy | 'always', string[]> = {
  docker: [
    'Dockerfile',
    'docker-compose.yml',
    'docker-compose.dev.yml',
    '.dockerignore',
    'nginx/',
  ],
  vercel: [], // No specific files (uses Next.js defaults)
  always: ['.github/'], // Keep for both strategies
};

const CODING_TOOL_OPTIONS = [
  { key: 'claude', name: 'Claude Code', desc: '.claude/, CLAUDE.md' },
  { key: 'cursor', name: 'Cursor', desc: '.cursor/' },
  { key: 'windsurf', name: 'Windsurf', desc: '.windsurfrules' },
] as const;

const DEPLOYMENT_OPTIONS = [
  { key: 'vercel', name: 'Vercel', desc: 'Recommended for Next.js' },
  { key: 'docker', name: 'Docker / Self-hosted', desc: 'Dockerfile, docker-compose, nginx' },
] as const;

// =============================================================================
// HELPERS
// =============================================================================

function log(message: string, type: 'info' | 'success' | 'error' | 'warn' = 'info') {
  const icons = {
    info: '',
    success: '',
    error: '',
    warn: '',
  };
  console.log(`${icons[type]} ${message}`);
}

async function prompt(question: string): Promise<string> {
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });

  return new Promise((resolve) => {
    rl.question(question, (answer) => {
      rl.close();
      resolve(answer.trim());
    });
  });
}

function fileExists(filePath: string): boolean {
  return fs.existsSync(path.join(process.cwd(), filePath));
}

function getFilesToGitignore(
  selectedTools: CodingTool[],
  deployment: DeploymentStrategy
): string[] {
  const toGitignore: string[] = [];

  // AI tools not selected
  for (const tool of ['claude', 'cursor', 'windsurf'] as CodingTool[]) {
    if (!selectedTools.includes(tool)) {
      toGitignore.push(...CODING_TOOL_FILES[tool]);
    }
  }

  // If no AI tools selected, also gitignore AGENTS.md
  if (selectedTools.length === 0) {
    toGitignore.push(...CODING_TOOL_FILES.shared);
  }

  // Deployment files
  if (deployment === 'vercel') {
    toGitignore.push(...DEPLOYMENT_FILES.docker);
  }
  // Docker keeps all its files, no need to gitignore vercel (no specific files)

  // Filter to only existing files
  return toGitignore.filter(fileExists);
}

function readGitignore(): string {
  const gitignorePath = path.join(process.cwd(), '.gitignore');
  if (fs.existsSync(gitignorePath)) {
    return fs.readFileSync(gitignorePath, 'utf-8');
  }
  return '';
}

function writeGitignore(content: string): void {
  const gitignorePath = path.join(process.cwd(), '.gitignore');
  fs.writeFileSync(gitignorePath, content, 'utf-8');
}

function addToGitignore(files: string[]): void {
  let gitignore = readGitignore();

  // Remove existing stack selector section if present
  const markerIndex = gitignore.indexOf(GITIGNORE_MARKER);
  if (markerIndex !== -1) {
    gitignore = gitignore.substring(0, markerIndex).trimEnd();
  }

  // Add new section
  if (files.length > 0) {
    const newSection = `\n\n${GITIGNORE_MARKER}\n# Auto-generated by setup-stack.ts - do not edit manually\n${files.join('\n')}\n`;
    gitignore += newSection;
  }

  writeGitignore(gitignore);
}

function removeFromGitignore(): void {
  let gitignore = readGitignore();

  // Remove stack selector section
  const markerIndex = gitignore.indexOf(GITIGNORE_MARKER);
  if (markerIndex !== -1) {
    gitignore = gitignore.substring(0, markerIndex).trimEnd() + '\n';
    writeGitignore(gitignore);
  }
}

function loadConfig(): StackConfig | null {
  const configPath = path.join(process.cwd(), CONFIG_FILE);
  if (fs.existsSync(configPath)) {
    try {
      return JSON.parse(fs.readFileSync(configPath, 'utf-8'));
    } catch {
      return null;
    }
  }
  return null;
}

function saveConfig(config: StackConfig): void {
  const configPath = path.join(process.cwd(), CONFIG_FILE);
  fs.writeFileSync(configPath, JSON.stringify(config, null, 2), 'utf-8');
}

function deleteConfig(): void {
  const configPath = path.join(process.cwd(), CONFIG_FILE);
  if (fs.existsSync(configPath)) {
    fs.unlinkSync(configPath);
  }
}

// =============================================================================
// COMMANDS
// =============================================================================

async function showList(): Promise<void> {
  const config = loadConfig();

  console.log('\n Stack Selector Configuration\n');

  if (!config) {
    console.log('No stack configuration found.');
    console.log('Run `npx tsx scripts/setup/setup-stack.ts` to configure.\n');
    return;
  }

  console.log(`Selected at: ${config.selectedAt}\n`);

  console.log('AI Coding Tools:');
  if (config.codingTools.length === 0) {
    console.log('  None selected (all gitignored)');
  } else {
    for (const tool of config.codingTools) {
      const option = CODING_TOOL_OPTIONS.find((o) => o.key === tool);
      console.log(`   ${option?.name || tool}`);
    }
  }

  console.log(`\nDeployment: ${config.deployment === 'vercel' ? 'Vercel' : 'Docker / Self-hosted'}`);

  if (config.gitignored.length > 0) {
    console.log('\nGitignored files/folders:');
    for (const file of config.gitignored) {
      console.log(`   ${file}`);
    }
  }

  console.log();
}

async function restore(): Promise<void> {
  console.log('\n Restoring Stack Configuration\n');

  const config = loadConfig();

  if (!config) {
    log('No stack configuration found. Nothing to restore.', 'warn');
    return;
  }

  // Remove from .gitignore
  removeFromGitignore();
  log('Removed entries from .gitignore', 'success');

  // Delete config file
  deleteConfig();
  log('Deleted .stack-config.json', 'success');

  console.log('\n Stack configuration restored!');
  console.log('All files are now tracked by git again.\n');
}

async function runInteractive(): Promise<void> {
  console.log(`
 Stack Selector (Optional)

This step helps reduce boilerplate bloat by gitignoring unused
configurations. You can skip this to keep all options.
`);

  // Check if already configured
  const existingConfig = loadConfig();
  if (existingConfig) {
    console.log(' Stack already configured.');
    console.log(`  - AI Tools: ${existingConfig.codingTools.join(', ') || 'none'}`);
    console.log(`  - Deployment: ${existingConfig.deployment}\n`);

    const reconfigure = await prompt('Reconfigure? (y/N): ');
    if (reconfigure.toLowerCase() !== 'y') {
      console.log('\nKeeping existing configuration.\n');
      return;
    }
    console.log();
  }

  // === AI Coding Tools Selection ===
  console.log(' Which AI coding tool(s) will you use? (select multiple with commas)\n');

  for (let i = 0; i < CODING_TOOL_OPTIONS.length; i++) {
    const option = CODING_TOOL_OPTIONS[i];
    console.log(`   [${i + 1}] ${option.name.padEnd(15)} - ${option.desc}`);
  }
  console.log(`   [a] All / Keep all (default)`);
  console.log(`   [s] Skip this step\n`);

  const toolsAnswer = await prompt('Your choice: ');

  if (toolsAnswer.toLowerCase() === 's') {
    console.log('\nSkipped. All configurations kept.\n');
    return;
  }

  let selectedTools: CodingTool[] = [];

  if (toolsAnswer.toLowerCase() === 'a' || toolsAnswer === '') {
    selectedTools = ['claude', 'cursor', 'windsurf'];
  } else {
    const indices = toolsAnswer.split(',').map((s) => parseInt(s.trim()) - 1);
    selectedTools = indices
      .filter((i) => i >= 0 && i < CODING_TOOL_OPTIONS.length)
      .map((i) => CODING_TOOL_OPTIONS[i].key) as CodingTool[];
  }

  // === Deployment Selection ===
  console.log('\n Which deployment strategy will you use?\n');

  for (let i = 0; i < DEPLOYMENT_OPTIONS.length; i++) {
    const option = DEPLOYMENT_OPTIONS[i];
    console.log(`   [${i + 1}] ${option.name.padEnd(25)} - ${option.desc}`);
  }
  console.log(`   [s] Skip this step\n`);

  const deployAnswer = await prompt('Your choice: ');

  if (deployAnswer.toLowerCase() === 's') {
    console.log('\nSkipped. All configurations kept.\n');
    return;
  }

  let deployment: DeploymentStrategy = 'vercel'; // default

  const deployIndex = parseInt(deployAnswer) - 1;
  if (deployIndex >= 0 && deployIndex < DEPLOYMENT_OPTIONS.length) {
    deployment = DEPLOYMENT_OPTIONS[deployIndex].key;
  }

  // === Calculate files to gitignore ===
  const toGitignore = getFilesToGitignore(selectedTools, deployment);

  // === Show summary ===
  console.log('\n Based on your selections:\n');

  // Show what's kept
  const keptTools = selectedTools.map((t) => {
    const option = CODING_TOOL_OPTIONS.find((o) => o.key === t);
    return option?.desc || t;
  });
  if (keptTools.length > 0) {
    console.log(`    Keep: ${keptTools.join(', ')}`);
  }
  if (deployment === 'docker') {
    console.log(`    Keep: Dockerfile, docker-compose*.yml, nginx/`);
  }

  // Show what's gitignored
  if (toGitignore.length > 0) {
    console.log(`    Gitignore: ${toGitignore.join(', ')}`);
  } else {
    console.log(`    No files to gitignore (keeping all)`);
  }

  console.log();

  if (toGitignore.length === 0) {
    console.log(' No changes needed - all files kept.\n');
    return;
  }

  const confirm = await prompt('Proceed? (Y/n): ');
  if (confirm.toLowerCase() === 'n') {
    console.log('\nCancelled. No changes made.\n');
    return;
  }

  // === Apply changes ===

  // Update .gitignore
  addToGitignore(toGitignore);

  // Save config
  const config: StackConfig = {
    selectedAt: new Date().toISOString(),
    codingTools: selectedTools,
    deployment,
    gitignored: toGitignore,
  };
  saveConfig(config);

  console.log(`\n Stack configured!`);
  console.log(`   Added ${toGitignore.length} entries to .gitignore`);
  console.log(`   Created ${CONFIG_FILE} for recovery\n`);

  console.log(' To restore all files later, run:');
  console.log('   npx tsx scripts/setup/setup-stack.ts --restore\n');
}

// =============================================================================
// MAIN
// =============================================================================

async function main() {
  const args = process.argv.slice(2);

  if (args.includes('--list') || args.includes('-l')) {
    await showList();
    return;
  }

  if (args.includes('--restore') || args.includes('-r')) {
    await restore();
    return;
  }

  if (args.includes('--help') || args.includes('-h')) {
    console.log(`
 ShipKit Stack Selector

Reduces boilerplate bloat by gitignoring unused configurations.

Usage:
  npx tsx scripts/setup/setup-stack.ts           Interactive mode
  npx tsx scripts/setup/setup-stack.ts --list    Show current config
  npx tsx scripts/setup/setup-stack.ts --restore Restore gitignored files
  npx tsx scripts/setup/setup-stack.ts --help    Show this help
`);
    return;
  }

  await runInteractive();
}

main().catch(console.error);
